M48
; DRILL file {KiCad 9.0.5} date 2026-03-27T22:44:40+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-27T22:44:40+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X118.0Y-69.5
X118.0Y-123.5
X172.0Y-69.5
X172.0Y-123.5
M30
